title: Muhammad Bahru Sholahuddin
description: Welcome to my portfolio page.

tagline:               
  Marine Robotics 
  & Renewable Controls

url: "https://mbsbahru.github.io"
baseurl: ''

lang:                  en

remote_theme: hydecorp/hydejack@v9
logo: /assets/img/logo_mydas.png

permalink:             /:categories/:year-:month-:day-:title/

paginate:              10
paginate_path:         /:num/

menu:
  - title: "LinkedIn"
    url:   https://www.linkedin.com/in/mbsbahru/
  - title: "GitHub"
    url:   https://github.com/mbsbahru
