title: Muhammad Bahru Sholahuddin
description: Welcome to my portfolio page.
tagline: Marine Robotics \n and Renewable Energy Controls

url: "https://mbsbahru.github.io"
baseurl: '/mbsbahru.github.io'

lang:                  en

remote_theme: hydecorp/hydejack@v9
logo: /assets/img/logo_mydas.png

author:
  name:                Muhammad Bahru Sholahuddin
  email:               mbsbahru@umich.edu
  github:              mbsbahru
  linkedin:            mbsbahru

permalink:             /:categories/:year-:month-:day-:title/

paginate:              10
paginate_path:         /:num/

plugins:
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-include-cache
  - jekyll-last-modified-at

social:
  name: mbsbahru
  links:
    - https://github.com/mbsbahru
    - https://linkedin.com/in/mbsbahru

kramdown:
  math_engine:         katex
  math_engine_opts:    {}
  footnote_backlink:   '&#x21a9;&#xfe0e;'

# Plugin Configs
# ---------------------------------------------------------------------------------------
optional_front_matter:
  remove_originals:    true

readme_index:
  remove_originals:    true
  with_frontmatter:    true

relative_links:
  collections:         true

titles_from_headings:
  strip_title:         true
  collections:         true

compress_html:
  comments:            ["<!--", "-->"]
  clippings:           all
  endings:             all
  ignore:
    envs:              [development]

sass:
  style:               compressed
