title: GH Web Pages
description: Welcome to my personal page.
url: "https://mbsbahru.github.io"
remote_theme: hydecorp/hydejack@v9

logo: /assets/img/logo_mydas.png

accent_image: /assets/img/sidebar-bg.jpg
accent_color: rgb(79,177,186)
theme_color: rgb(25,55,71)

plugins:
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-include-cache
  - jekyll-last-modified-at

social:
  name: mbsbahru
  links:
    - https://github.com/mbsbahru
    - https://linkedin.com/in/mbsbahru
